// @ts-ignore - browser ESM import is intentionally remote and pinned.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.95.0?bundle';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from './config.js';

type Restaurant = { id:string; name:string; slug:string; address:string|null; description:string|null; website:string|null; phone:string|null; latitude:number|null; longitude:number|null; active:boolean; plan_key:string; max_users:number; max_placements:number; feature_flags:Record<string,boolean>; stripe_customer_id:string|null; stripe_subscription_id:string|null; subscription_status:string|null; subscription_price_id:string|null; current_period_end:string|null };
type Membership = { restaurant_id:string; user_id:string; role:'owner'|'editor'|'viewer'; active:boolean };
type Placement = { id:string; restaurant_id:string|null; advertiser_name:string; campaign_name:string|null; name:string; address:string; description:string; latitude:number; longitude:number; active:boolean; starts_at:string; ends_at:string|null; cpm_rate_cents:number; currency:string; impression_count:number; created_at:string };
type AdminUser = { id:string; email:string; created_at:string; last_sign_in_at:string|null; memberships:Membership[] };

const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, { auth:{ persistSession:true, autoRefreshToken:true, detectSessionInUrl:true } });
const $ = <T extends HTMLElement = HTMLElement>(id:string) => document.getElementById(id) as T;
const views = { login:$('login-view'), password:$('password-view'), denied:$('denied-view'), portal:$('portal-view') };
let restaurants:Restaurant[]=[]; let memberships:Membership[]=[]; let placements:Placement[]=[]; let adminUsers:AdminUser[]=[];
let selectedRestaurantId=''; let editingPlacementId:string|null=null; let isAdmin=false;
let recoveringPassword = location.hash.includes('type=recovery') || new URLSearchParams(location.search).get('type') === 'recovery';

function showOnly(name:keyof typeof views){ Object.entries(views).forEach(([key,node])=>node.classList.toggle('hidden',key!==name)); $('sign-out').classList.toggle('hidden',name!=='portal'); }
function notice(message='',error=false){ const node=$('notice'); node.textContent=message; node.classList.toggle('hidden',!message); node.classList.toggle('error',error); }
function esc(value:unknown){ return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
function currentRestaurant(){ return restaurants.find(r=>r.id===selectedRestaurantId)??null; }
function canEditRestaurant(){ if(isAdmin)return true; const m=memberships.find(x=>x.restaurant_id===selectedRestaurantId&&x.active); return m?.role==='owner'||m?.role==='editor'; }
function money(cents:number,currency='USD'){ return new Intl.NumberFormat(undefined,{style:'currency',currency:/^[A-Z]{3}$/.test(currency)?currency:'USD'}).format((cents||0)/100); }
function localInput(value?:string|null){ if(!value)return ''; const d=new Date(value); const offset=d.getTimezoneOffset()*60000; return new Date(d.getTime()-offset).toISOString().slice(0,16); }
function iso(value:string){ const d=new Date(value); if(Number.isNaN(d.getTime()))throw new Error('Enter a valid date/time.'); return d.toISOString(); }
function placementStatus(p:Placement){ const now=Date.now(); if(!p.active)return ['Paused','']; if(new Date(p.starts_at).getTime()>now)return ['Scheduled','scheduled']; if(p.ends_at&&new Date(p.ends_at).getTime()<=now)return ['Ended','expired']; return ['Serving','active']; }
function spendCents(p:Placement){ return Math.round((Number(p.impression_count||0)*Number(p.cpm_rate_cents||0))/1000); }
async function invoke<T>(name:string,body:Record<string,unknown>={}){ const {data,error}=await supabase.functions.invoke(name,{body}); if(error)throw error; if(data?.error)throw new Error(data.error); return data as T; }

async function loadAccess(){
  const {data:{user},error}=await supabase.auth.getUser(); if(error||!user){showOnly('login');return;} $('session-label').textContent=user.email??'';
  const [{data:adminRows,error:adminError},{data:memberRows,error:memberError}]=await Promise.all([
    supabase.from('platform_admins').select('user_id').eq('user_id',user.id),
    supabase.from('restaurant_memberships').select('restaurant_id,user_id,role,active').eq('user_id',user.id).eq('active',true),
  ]);
  if(adminError)throw adminError; if(memberError)throw memberError; isAdmin=(adminRows?.length??0)>0; memberships=(memberRows??[]) as Membership[];
  let query=supabase.from('restaurants').select('*').order('name'); if(!isAdmin)query=query.in('id',memberships.map(m=>m.restaurant_id));
  const {data,error:restaurantsError}=await query; if(restaurantsError)throw restaurantsError; restaurants=(data??[]) as Restaurant[];
  if(!restaurants.length&&!isAdmin){showOnly('denied');return;} selectedRestaurantId=selectedRestaurantId&&restaurants.some(r=>r.id===selectedRestaurantId)?selectedRestaurantId:restaurants[0]?.id??'';
  showOnly('portal'); renderShell(); await Promise.all([loadPlacements(),isAdmin?loadAdminUsers():Promise.resolve()]);
}
function renderShell(){
  const r=currentRestaurant(); $('portal-title').textContent=r?.name??'Chowseek admin'; $('portal-subtitle').textContent=isAdmin?'Platform administrator — manage every restaurant, user, plan limit, and placement.':'Your restaurant profile, sponsored placements, and subscription.';
  $('admin-tab-button').classList.toggle('hidden',!isAdmin); $('restaurant-switcher-wrap').classList.toggle('hidden',restaurants.length<=1);
  const switcher=$('restaurant-switcher') as HTMLSelectElement; switcher.innerHTML=restaurants.map(x=>`<option value="${esc(x.id)}" ${x.id===selectedRestaurantId?'selected':''}>${esc(x.name)}</option>`).join('');
  const inviteRestaurant=$('invite-restaurant') as HTMLSelectElement; inviteRestaurant.innerHTML=restaurants.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');
  renderRestaurant(); renderBilling(); if(isAdmin)renderAdminRestaurants();
}
function renderRestaurant(){
  const r=currentRestaurant(); if(!r)return; ($('restaurant-name') as HTMLInputElement).value=r.name; ($('restaurant-address') as HTMLInputElement).value=r.address??''; ($('restaurant-phone') as HTMLInputElement).value=r.phone??''; ($('restaurant-website') as HTMLInputElement).value=r.website??''; ($('restaurant-description') as HTMLTextAreaElement).value=r.description??''; ($('restaurant-latitude') as HTMLInputElement).value=r.latitude?.toString()??''; ($('restaurant-longitude') as HTMLInputElement).value=r.longitude?.toString()??'';
  $('restaurant-status').textContent=r.active?'Active':'Disabled'; $('restaurant-status').className=`badge ${r.active?'active':'expired'}`;
  const members=adminUsers.filter(u=>u.memberships.some(m=>m.restaurant_id===r.id&&m.active)).length||memberships.filter(m=>m.restaurant_id===r.id&&m.active).length; $('stat-plan').textContent=r.plan_key||'free'; $('stat-users').textContent=`${members} / ${r.max_users}`; $('stat-placements').textContent=`${placements.length} / ${r.max_placements}`;
  Array.from(($('restaurant-form') as HTMLFormElement).elements).forEach(el=>(el as HTMLInputElement).disabled=!canEditRestaurant());
}
async function loadPlacements(){ if(!selectedRestaurantId){placements=[];renderPlacements();return;} const {data,error}=await supabase.from('sponsored_results').select('*').eq('restaurant_id',selectedRestaurantId).order('created_at',{ascending:false}); if(error)throw error; placements=(data??[]) as Placement[]; renderPlacements(); renderRestaurant(); }
function renderPlacements(){
  let serving=0,impressions=0,spend=0; for(const p of placements){if(placementStatus(p)[0]==='Serving')serving++; impressions+=Number(p.impression_count)||0; spend+=spendCents(p);} $('stat-serving').textContent=String(serving); $('stat-impressions').textContent=impressions.toLocaleString(); $('stat-spend').textContent=money(spend); $('placements-empty').classList.toggle('hidden',placements.length>0);
  $('placements-list').innerHTML=placements.map(p=>{const [status,cls]=placementStatus(p);return `<article class="offer"><div><div class="offer-meta"><span class="badge ${cls}">${status}</span>${p.campaign_name?`<span>Campaign: <strong>${esc(p.campaign_name)}</strong></span>`:''}</div><h3>${esc(p.name)}</h3><p class="address-line">${esc(p.address)}</p><p class="offer-note">${esc(p.description)}</p><div class="offer-meta detail-row"><span>${Number(p.impression_count).toLocaleString()} impressions</span><span>${money(spendCents(p),p.currency)} estimated</span><span>${money(p.cpm_rate_cents,p.currency)} CPM</span></div></div><div class="actions">${canEditRestaurant()?`<button class="secondary edit-placement" data-id="${esc(p.id)}">Edit</button><button class="secondary toggle-placement" data-id="${esc(p.id)}">${p.active?'Pause':'Activate'}</button>${p.impression_count===0?`<button class="danger delete-placement" data-id="${esc(p.id)}">Delete</button>`:''}`:''}</div></article>`;}).join('');
}
function renderBilling(){ const r=currentRestaurant(); if(!r)return; $('billing-status').textContent=r.subscription_status??'not subscribed'; $('billing-plan').textContent=r.plan_key||'free'; $('billing-renewal').textContent=r.current_period_end?new Date(r.current_period_end).toLocaleDateString():'—'; ($('manage-billing') as HTMLButtonElement).disabled=!r.stripe_customer_id; }
async function loadAdminUsers(){ if(!isAdmin)return; const data=await invoke<{users:AdminUser[]}>('restaurant-admin-users',{action:'list'}); adminUsers=data.users; renderAdminUsers(); renderRestaurant(); }
function renderAdminRestaurants(){ $('admin-restaurants').innerHTML=restaurants.map(r=>`<div class="admin-row"><div><strong>${esc(r.name)}</strong><span>${esc(r.plan_key)} · ${esc(r.subscription_status??'no subscription')}</span></div><div class="admin-controls"><label>Users <input class="limit-input admin-limit" data-id="${esc(r.id)}" data-field="max_users" type="number" min="1" value="${r.max_users}" /></label><label>Placements <input class="limit-input admin-limit" data-id="${esc(r.id)}" data-field="max_placements" type="number" min="0" value="${r.max_placements}" /></label><label class="check-row compact-check"><input class="admin-active" data-id="${esc(r.id)}" type="checkbox" ${r.active?'checked':''}/><span>Active</span></label></div></div>`).join(''); }
function renderAdminUsers(){ $('admin-users').innerHTML=adminUsers.map(u=>`<div class="admin-row"><div><strong>${esc(u.email)}</strong><span>${u.memberships.filter(m=>m.active).map(m=>`${esc(restaurants.find(r=>r.id===m.restaurant_id)?.name??'Unknown')} (${esc(m.role)})`).join(', ')||'No active restaurant'}</span></div><div class="actions">${u.memberships.map(m=>`<button class="secondary revoke-user" data-user="${esc(u.id)}" data-restaurant="${esc(m.restaurant_id)}">${m.active?'Remove access':'Restore access'}</button>`).join('')}<button class="danger delete-user" data-user="${esc(u.id)}">Delete account</button></div></div>`).join(''); }
function resetPlacementForm(){ editingPlacementId=null; ($('placement-form') as HTMLFormElement).reset(); ($('currency') as HTMLInputElement).value='USD'; ($('starts-at') as HTMLInputElement).value=localInput(new Date().toISOString()); $('placement-form-title').textContent='New placement'; $('save-placement').textContent='Create placement'; $('cancel-placement-edit').classList.add('hidden'); }
function fillPlacement(p:Placement){ editingPlacementId=p.id; ($('campaign-name') as HTMLInputElement).value=p.campaign_name??''; ($('place-name') as HTMLInputElement).value=p.name; ($('place-address') as HTMLInputElement).value=p.address; ($('place-description') as HTMLTextAreaElement).value=p.description; ($('place-latitude') as HTMLInputElement).value=String(p.latitude); ($('place-longitude') as HTMLInputElement).value=String(p.longitude); ($('starts-at') as HTMLInputElement).value=localInput(p.starts_at); ($('ends-at') as HTMLInputElement).value=localInput(p.ends_at); ($('cpm-rate') as HTMLInputElement).value=String(p.cpm_rate_cents/100); ($('currency') as HTMLInputElement).value=p.currency; ($('placement-active') as HTMLInputElement).checked=p.active; $('placement-form-title').textContent='Edit placement'; $('save-placement').textContent='Save changes'; $('cancel-placement-edit').classList.remove('hidden'); window.scrollTo({top:0,behavior:'smooth'}); }

$('login-form').addEventListener('submit',async event=>{event.preventDefault();notice();const email=($('login-email') as HTMLInputElement).value.trim();const password=($('login-password') as HTMLInputElement).value;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return notice(error.message,true);await loadAccess().catch((e:Error)=>notice(e.message,true));});
$('reset-password').addEventListener('click',async()=>{const email=($('login-email') as HTMLInputElement).value.trim();if(!email)return notice('Enter your email first.',true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});notice(error?error.message:'Password reset email sent.',!!error);});
$('password-form').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.auth.updateUser({password:($('new-password') as HTMLInputElement).value});if(error)return notice(error.message,true);recoveringPassword=false;history.replaceState({},'',location.pathname);await loadAccess();});
$('sign-out').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload();});
$('restaurant-switcher').addEventListener('change',async e=>{selectedRestaurantId=(e.target as HTMLSelectElement).value;resetPlacementForm();renderShell();await loadPlacements();});
document.querySelectorAll<HTMLButtonElement>('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));$(`tab-${button.dataset.tab}`).classList.remove('hidden');}));
$('restaurant-form').addEventListener('submit',async e=>{e.preventDefault();if(!canEditRestaurant())return;const payload={name:($('restaurant-name') as HTMLInputElement).value.trim(),address:($('restaurant-address') as HTMLInputElement).value.trim()||null,phone:($('restaurant-phone') as HTMLInputElement).value.trim()||null,website:($('restaurant-website') as HTMLInputElement).value.trim()||null,description:($('restaurant-description') as HTMLTextAreaElement).value.trim()||null,latitude:Number(($('restaurant-latitude') as HTMLInputElement).value)||null,longitude:Number(($('restaurant-longitude') as HTMLInputElement).value)||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('restaurants').update(payload).eq('id',selectedRestaurantId);if(error)return notice(error.message,true);notice('Restaurant saved.');await loadAccess();});
$('placement-form').addEventListener('submit',async e=>{e.preventDefault();if(!canEditRestaurant())return;const r=currentRestaurant();if(!r)return;try{const wasEditing=!!editingPlacementId;const payload={restaurant_id:r.id,advertiser_name:r.name,campaign_name:($('campaign-name') as HTMLInputElement).value.trim()||null,name:($('place-name') as HTMLInputElement).value.trim(),address:($('place-address') as HTMLInputElement).value.trim(),description:($('place-description') as HTMLTextAreaElement).value.trim(),latitude:Number(($('place-latitude') as HTMLInputElement).value),longitude:Number(($('place-longitude') as HTMLInputElement).value),starts_at:iso(($('starts-at') as HTMLInputElement).value),ends_at:($('ends-at') as HTMLInputElement).value?iso(($('ends-at') as HTMLInputElement).value):null,cpm_rate_cents:Math.round(Number(($('cpm-rate') as HTMLInputElement).value)*100),currency:($('currency') as HTMLInputElement).value.trim().toUpperCase(),active:($('placement-active') as HTMLInputElement).checked,updated_at:new Date().toISOString()};const result=editingPlacementId?await supabase.from('sponsored_results').update(payload).eq('id',editingPlacementId):await supabase.from('sponsored_results').insert(payload);if(result.error)throw result.error;resetPlacementForm();notice(wasEditing?'Placement saved.':'Placement created.');await loadPlacements();}catch(err){notice((err as Error).message,true);}});
$('cancel-placement-edit').addEventListener('click',resetPlacementForm);$('refresh-placements').addEventListener('click',()=>loadPlacements().catch((e:Error)=>notice(e.message,true)));
$('placements-list').addEventListener('click',async e=>{const target=e.target as HTMLElement;const id=target.dataset.id;if(!id)return;const p=placements.find(x=>x.id===id);if(!p)return;if(target.classList.contains('edit-placement'))return fillPlacement(p);if(target.classList.contains('toggle-placement')){const {error}=await supabase.from('sponsored_results').update({active:!p.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)return notice(error.message,true);await loadPlacements();}if(target.classList.contains('delete-placement')){if(!confirm('Delete this unused placement?'))return;const {error}=await supabase.from('sponsored_results').delete().eq('id',id);if(error)return notice(error.message,true);await loadPlacements();}});
document.querySelectorAll<HTMLButtonElement>('.checkout-plan').forEach(button=>button.addEventListener('click',async()=>{try{const data=await invoke<{url:string}>('restaurant-stripe-checkout',{restaurant_id:selectedRestaurantId,plan_key:button.dataset.plan});location.href=data.url;}catch(e){notice((e as Error).message,true);}}));
$('manage-billing').addEventListener('click',async()=>{try{const data=await invoke<{url:string}>('restaurant-stripe-portal',{restaurant_id:selectedRestaurantId});location.href=data.url;}catch(e){notice((e as Error).message,true);}});
$('create-restaurant-form').addEventListener('submit',async e=>{e.preventDefault();const name=($('new-restaurant-name') as HTMLInputElement).value.trim();const slug=`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${crypto.randomUUID().slice(0,8)}`;const {error}=await supabase.from('restaurants').insert({name,slug});if(error)return notice(error.message,true);($('new-restaurant-name') as HTMLInputElement).value='';await loadAccess();});
$('invite-user-form').addEventListener('submit',async e=>{e.preventDefault();try{await invoke('restaurant-admin-users',{action:'invite',email:($('invite-email') as HTMLInputElement).value.trim(),restaurant_id:($('invite-restaurant') as HTMLSelectElement).value,role:($('invite-role') as HTMLSelectElement).value});($('invite-email') as HTMLInputElement).value='';notice('Invitation sent.');await loadAdminUsers();}catch(err){notice((err as Error).message,true);}});
$('refresh-admin').addEventListener('click',async()=>{await loadAccess();});
$('admin-restaurants').addEventListener('change',async e=>{const t=e.target as HTMLInputElement;const id=t.dataset.id;if(!id)return;const patch:Record<string,unknown>={action:'update_restaurant',restaurant_id:id};if(t.classList.contains('admin-limit'))patch[t.dataset.field!]=Number(t.value);if(t.classList.contains('admin-active'))patch.active=t.checked;try{await invoke('restaurant-admin-users',patch);notice('Restaurant limits updated.');await loadAccess();}catch(err){notice((err as Error).message,true);}});
$('admin-users').addEventListener('click',async e=>{const t=e.target as HTMLElement;try{if(t.classList.contains('revoke-user')){const u=adminUsers.find(x=>x.id===t.dataset.user);const m=u?.memberships.find(x=>x.restaurant_id===t.dataset.restaurant);await invoke('restaurant-admin-users',{action:'set_access',user_id:t.dataset.user,restaurant_id:t.dataset.restaurant,active:!m?.active});await loadAdminUsers();}if(t.classList.contains('delete-user')){if(!confirm('Permanently delete this user account?'))return;await invoke('restaurant-admin-users',{action:'delete',user_id:t.dataset.user});await loadAdminUsers();}}catch(err){notice((err as Error).message,true);}});
supabase.auth.onAuthStateChange(()=>{if(!recoveringPassword)void loadAccess().catch((e:Error)=>notice(e.message,true));});
if(recoveringPassword)showOnly('password');else void loadAccess().catch((e:Error)=>{showOnly('login');notice(e.message,true);});
resetPlacementForm();