-- Chowseek multi-tenant restaurant portal.
-- This migration is intentionally designed for the existing Chowseek Supabase project.
-- Existing sponsored_results rows are preserved under a Legacy / Unassigned restaurant
-- until a platform admin assigns them to a restaurant.

create schema if not exists chowseek_private;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 200),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  address text,
  description text,
  website text,
  phone text,
  latitude double precision check (latitude is null or latitude between -90 and 90),
  longitude double precision check (longitude is null or longitude between -180 and 180),
  active boolean not null default true,
  plan_key text not null default 'free',
  max_users integer not null default 2 check (max_users >= 1),
  max_placements integer not null default 3 check (max_placements >= 0),
  feature_flags jsonb not null default '{}'::jsonb,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text,
  subscription_price_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_memberships (
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner','editor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (restaurant_id, user_id)
);

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Carry forward anyone already authorized by the legacy sponsorship portal.
insert into public.platform_admins (user_id)
select user_id from chowseek_private.portal_admins
on conflict (user_id) do nothing;

create table if not exists public.portal_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  restaurant_id uuid references public.restaurants(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Separate from Chowseek's existing consumer stripe_webhook_events table.
create table if not exists public.restaurant_stripe_events (
  event_id text primary key,
  event_type text not null,
  processed_at timestamptz not null default now()
);

alter table public.sponsored_results
  add column if not exists restaurant_id uuid references public.restaurants(id) on delete restrict;

insert into public.restaurants (id, name, slug, active, max_users, max_placements)
values ('00000000-0000-0000-0000-000000000001', 'Legacy / Unassigned', 'legacy-unassigned', false, 1, 100000)
on conflict (id) do nothing;

update public.sponsored_results
set restaurant_id = '00000000-0000-0000-0000-000000000001'
where restaurant_id is null;

create index if not exists sponsored_results_restaurant_id_idx on public.sponsored_results(restaurant_id);
create index if not exists restaurant_memberships_user_id_idx on public.restaurant_memberships(user_id) where active;
create index if not exists portal_audit_log_restaurant_created_idx on public.portal_audit_log(restaurant_id, created_at desc);

create or replace function chowseek_private.is_platform_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_user_id is not null and exists (
    select 1 from public.platform_admins pa where pa.user_id = p_user_id
  );
$$;

create or replace function chowseek_private.has_restaurant_role(
  p_restaurant_id uuid,
  p_roles text[] default array['owner','editor','viewer']::text[],
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_user_id is not null and exists (
    select 1
    from public.restaurant_memberships rm
    where rm.restaurant_id = p_restaurant_id
      and rm.user_id = p_user_id
      and rm.active
      and rm.role = any(p_roles)
  );
$$;

revoke all on function chowseek_private.is_platform_admin(uuid) from public;
revoke all on function chowseek_private.has_restaurant_role(uuid,text[],uuid) from public;
grant usage on schema chowseek_private to authenticated;
grant execute on function chowseek_private.is_platform_admin(uuid) to authenticated;
grant execute on function chowseek_private.has_restaurant_role(uuid,text[],uuid) to authenticated;

create or replace function chowseek_private.enforce_membership_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare v_limit integer; v_count integer;
begin
  if new.active and (tg_op = 'INSERT' or old.active is distinct from true or old.restaurant_id is distinct from new.restaurant_id) then
    select max_users into v_limit from public.restaurants where id = new.restaurant_id for update;
    select count(*) into v_count
    from public.restaurant_memberships
    where restaurant_id = new.restaurant_id and active and user_id <> new.user_id;
    if v_count >= v_limit then
      raise exception 'Restaurant user limit reached (%).', v_limit using errcode = 'P0001';
    end if;
  end if;
  return new;
end;
$$;

create or replace function chowseek_private.enforce_placement_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare v_limit integer; v_count integer;
begin
  if new.restaurant_id is null then return new; end if;
  if tg_op = 'INSERT' or old.restaurant_id is distinct from new.restaurant_id then
    select max_placements into v_limit from public.restaurants where id = new.restaurant_id for update;
    select count(*) into v_count
    from public.sponsored_results
    where restaurant_id = new.restaurant_id and (tg_op = 'INSERT' or id <> new.id);
    if v_count >= v_limit then
      raise exception 'Restaurant placement limit reached (%).', v_limit using errcode = 'P0001';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_membership_limit on public.restaurant_memberships;
create trigger enforce_membership_limit
before insert or update of restaurant_id, active on public.restaurant_memberships
for each row execute function chowseek_private.enforce_membership_limit();

drop trigger if exists enforce_placement_limit on public.sponsored_results;
create trigger enforce_placement_limit
before insert or update of restaurant_id on public.sponsored_results
for each row execute function chowseek_private.enforce_placement_limit();

create or replace function chowseek_private.audit_portal_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare payload jsonb; rid uuid; tid text;
begin
  payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  rid := case
    when tg_table_name = 'restaurants' and tg_op = 'DELETE' then null
    when tg_table_name = 'restaurants' then (payload->>'id')::uuid
    else nullif(payload->>'restaurant_id','')::uuid
  end;
  tid := coalesce(payload->>'id', payload->>'user_id');
  insert into public.portal_audit_log(actor_user_id, restaurant_id, action, target_type, target_id, details)
  values (auth.uid(), rid, lower(tg_op), tg_table_name, tid, jsonb_build_object('row', payload));
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists audit_restaurants on public.restaurants;
create trigger audit_restaurants
after insert or update or delete on public.restaurants
for each row execute function chowseek_private.audit_portal_change();

drop trigger if exists audit_memberships on public.restaurant_memberships;
create trigger audit_memberships
after insert or update or delete on public.restaurant_memberships
for each row execute function chowseek_private.audit_portal_change();

-- Do not audit impression_count-only updates from the mobile app.
drop trigger if exists audit_sponsored_results on public.sponsored_results;
drop trigger if exists audit_sponsored_results_insert_delete on public.sponsored_results;
drop trigger if exists audit_sponsored_results_update on public.sponsored_results;
create trigger audit_sponsored_results_insert_delete
after insert or delete on public.sponsored_results
for each row execute function chowseek_private.audit_portal_change();
create trigger audit_sponsored_results_update
after update of restaurant_id, advertiser_name, campaign_name, name, address, description,
  latitude, longitude, active, starts_at, ends_at, cpm_rate_cents, currency
on public.sponsored_results
for each row execute function chowseek_private.audit_portal_change();

alter table public.restaurants enable row level security;
alter table public.restaurant_memberships enable row level security;
alter table public.platform_admins enable row level security;
alter table public.portal_audit_log enable row level security;
alter table public.restaurant_stripe_events enable row level security;
alter table public.sponsored_results enable row level security;

-- Remove the legacy static-portal policies so these tenant policies are authoritative.
drop policy if exists "portal admins can read sponsored results" on public.sponsored_results;
drop policy if exists "portal admins can create sponsored results" on public.sponsored_results;
drop policy if exists "portal admins can update sponsored results" on public.sponsored_results;
drop policy if exists "portal admins can delete unused sponsored results" on public.sponsored_results;

-- Admin detection: users can only read their own admin marker.
drop policy if exists "users read own platform admin marker" on public.platform_admins;
create policy "users read own platform admin marker"
on public.platform_admins for select to authenticated
using (user_id = (select auth.uid()));

-- Restaurants.
drop policy if exists "restaurant members read restaurants" on public.restaurants;
create policy "restaurant members read restaurants"
on public.restaurants for select to authenticated
using (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(id));

drop policy if exists "restaurant editors update profile" on public.restaurants;
create policy "restaurant editors update profile"
on public.restaurants for update to authenticated
using (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(id, array['owner','editor']))
with check (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(id, array['owner','editor']));

drop policy if exists "platform admins create restaurants" on public.restaurants;
create policy "platform admins create restaurants"
on public.restaurants for insert to authenticated
with check (chowseek_private.is_platform_admin());

drop policy if exists "platform admins delete restaurants" on public.restaurants;
create policy "platform admins delete restaurants"
on public.restaurants for delete to authenticated
using (chowseek_private.is_platform_admin());

-- Memberships are readable by the member or platform admins. All writes are trusted-server only.
drop policy if exists "members read memberships" on public.restaurant_memberships;
create policy "members read memberships"
on public.restaurant_memberships for select to authenticated
using (user_id = (select auth.uid()) or chowseek_private.is_platform_admin());

-- Sponsored placements.
drop policy if exists "restaurant users read placements" on public.sponsored_results;
create policy "restaurant users read placements"
on public.sponsored_results for select to authenticated
using (
  chowseek_private.is_platform_admin()
  or (restaurant_id is not null and chowseek_private.has_restaurant_role(restaurant_id))
);

drop policy if exists "restaurant editors create placements" on public.sponsored_results;
create policy "restaurant editors create placements"
on public.sponsored_results for insert to authenticated
with check (
  restaurant_id is not null
  and (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(restaurant_id, array['owner','editor']))
);

drop policy if exists "restaurant editors update placements" on public.sponsored_results;
create policy "restaurant editors update placements"
on public.sponsored_results for update to authenticated
using (
  restaurant_id is not null
  and (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(restaurant_id, array['owner','editor']))
)
with check (
  restaurant_id is not null
  and (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(restaurant_id, array['owner','editor']))
);

drop policy if exists "restaurant editors delete unused placements" on public.sponsored_results;
create policy "restaurant editors delete unused placements"
on public.sponsored_results for delete to authenticated
using (
  coalesce(impression_count,0) = 0
  and restaurant_id is not null
  and (chowseek_private.is_platform_admin() or chowseek_private.has_restaurant_role(restaurant_id, array['owner','editor']))
);

-- Audit log is visible to platform admins, plus restaurant owners for their own restaurant.
drop policy if exists "authorized users read audit log" on public.portal_audit_log;
create policy "authorized users read audit log"
on public.portal_audit_log for select to authenticated
using (
  chowseek_private.is_platform_admin()
  or (restaurant_id is not null and chowseek_private.has_restaurant_role(restaurant_id, array['owner']))
);

revoke all on public.restaurants, public.restaurant_memberships, public.platform_admins,
  public.portal_audit_log, public.restaurant_stripe_events from anon;

grant select on public.restaurants, public.restaurant_memberships, public.platform_admins,
  public.portal_audit_log to authenticated;
grant insert(name, slug) on public.restaurants to authenticated;
grant update(name,address,description,website,phone,latitude,longitude,updated_at)
  on public.restaurants to authenticated;
grant select, delete on public.sponsored_results to authenticated;
revoke insert, update on public.sponsored_results from authenticated;
grant insert(restaurant_id,advertiser_name,campaign_name,name,address,description,latitude,longitude,
  active,starts_at,ends_at,cpm_rate_cents,currency,updated_at)
  on public.sponsored_results to authenticated;
grant update(restaurant_id,advertiser_name,campaign_name,name,address,description,latitude,longitude,
  active,starts_at,ends_at,cpm_rate_cents,currency,updated_at)
  on public.sponsored_results to authenticated;

-- restaurant_stripe_events intentionally has no authenticated policies/grants; secret-key only.
